 <?php $posts = $this->getPosts(); ?>
<?php if (count($posts)): ?>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
    <?php foreach ($posts as $post): ?>
        <div class="postWrapper">
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            </div>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
            <?php echo $this->getBookmarkHtml($post) ?>
            <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
        </div>
    <?php endforeach; ?>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php else: ?>
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>